## This section is for configuration parameters of the Wifi_Gatherer.py file
snmp:
  input_from_file: False
  input_file_name:
  community: <enter community string>
  controller_ip: <enter controller ip address here>
  count_oid: ".1.3.6.1.4.1.14179.2.1.5.1.1"

## This section is for the configuration parameters of your data_processor.py (or any file that inherits this) file
data_processor:
  count_oid: ".1.3.6.1.4.1.14179.2.1.5.1.1"
  #add any configuration parameters specific to your implementation of the data processor here

local_db:
  filename: sqlite:///%s/wifi_buffer.db
  table: wifi_buffer_table

remote_db:
  host: https://localhost
  port: 8086
  ssl: false
  verify_ssl: false
  database: wifi_device_count_db
  username:
  password:
  measurement: wifi_count
